// Here we implement our methods that are generated by tscodegen.
// Every function gets the JSI runtime. For most methods we do not
// need this.

// For opening dynamic libraries
#include<dlfcn.h>

#include "react-native-multiply-module.h"
#include "../lib/cpp-generated/NativeModules.cpp"
#include "Logging.h"
#include "rust_multiply.h"

using namespace facebook;
using namespace react;

NativeMultiply::NativeMultiply(std::shared_ptr<CallInvoker> jsInvoker): MultiplyModuleCxxSpecJSI(jsInvoker) {};

double NativeMultiply::multiply(jsi::Runtime &rt, double a, double b) {
    return rust_multiply();
}
