// Here we implement our methods that are generated by tscodegen.
// Every function gets the JSI runtime. For most methods we do not
// need this.

#include "react-native-multiply-module.h"

using namespace facebook;
using namespace react;


double NativeMultiply::multiply(jsi::Runtime &rt, double a, double b) {
    return a * b;
}
