/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#include <react/modules/MultiplyModule/NativeModules.h>

namespace facebook {
namespace react {

static jsi::Value __hostFunction_MultiplyModuleCxxSpecJSI_multiply(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<MultiplyModuleCxxSpecJSI *>(&turboModule)->multiply(rt, args[0].getNumber(), args[1].getNumber());
}

MultiplyModuleCxxSpecJSI::MultiplyModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("MultiplyModule", jsInvoker) {
  methodMap_["multiply"] = MethodMetadata {2, __hostFunction_MultiplyModuleCxxSpecJSI_multiply};
}


} // namespace react
} // namespace facebook
